# Generated by Django 2.1.7 on 2019-03-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=30)),
                ('username', models.CharField(max_length=10)),
                ('phmun', models.IntegerField()),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='signup',
            fields=[
                ('firstname', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('lastname', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('pincode', models.IntegerField()),
                ('about', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=30)),
                ('phmun', models.IntegerField()),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
                ('confpass', models.CharField(max_length=10)),
                ('answer', models.CharField(max_length=20)),
            ],
        ),
    ]
