# Generated by Django 2.1.7 on 2019-03-28 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detailapp', '0002_auto_20190328_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signin',
            name='phnum',
            field=models.CharField(max_length=15),
        ),
    ]
