# Generated by Django 2.1.7 on 2019-03-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detailapp', '0004_auto_20190328_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signin',
            name='phnum',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='signup',
            name='phnum',
            field=models.IntegerField(),
        ),
    ]
