# Generated by Django 2.1.7 on 2019-03-28 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detailapp', '0005_auto_20190328_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signin',
            name='phnum',
        ),
    ]
